receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlphttp:
    endpoint: "http://logstash:4320"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp]
